Default: &defaults
  database: Website.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Website_test.sqlite3
  <<: *defaults

Staging:
  database: Website_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Website_production.sqlite3
  poolsize: 100
  <<: *defaults
